// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAccount = `-- name: ArchiveAccount :execrows
UPDATE accounts
SET archived_at = COALESCE(archived_at, now()),
    updated_at = CASE WHEN archived_at IS NULL THEN now() ELSE updated_at END
WHERE workspace_id = $1
  AND id = $2
`

type ArchiveAccountParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) ArchiveAccount(ctx context.Context, arg ArchiveAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAccount, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
    id, workspace_id, name, type, currency, institution_name
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateAccountParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Currency        string      `json:"currency"`
	InstitutionName pgtype.Text `json:"institution_name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.InstitutionName,
	)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT
    accounts.id,
    accounts.workspace_id,
    accounts.name,
    accounts.type,
    accounts.currency,
    accounts.institution_name,
    accounts.archived_at,
    COALESCE(SUM(
        CASE
            WHEN transactions.status = 'posted' AND transactions.deleted_at IS NULL
                THEN transaction_entries.amount_minor
            ELSE 0
        END
    ), 0)::BIGINT AS balance_minor
FROM accounts
LEFT JOIN transaction_entries
    ON transaction_entries.workspace_id = accounts.workspace_id
   AND transaction_entries.account_id = accounts.id
LEFT JOIN transactions
    ON transactions.workspace_id = transaction_entries.workspace_id
   AND transactions.id = transaction_entries.transaction_id
WHERE accounts.workspace_id = $1
  AND accounts.id = $2
GROUP BY accounts.id
`

type GetAccountParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetAccountRow struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Name            string             `json:"name"`
	Type            string             `json:"type"`
	Currency        string             `json:"currency"`
	InstitutionName pgtype.Text        `json:"institution_name"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	BalanceMinor    int64              `json:"balance_minor"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.WorkspaceID, arg.ID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InstitutionName,
		&i.ArchivedAt,
		&i.BalanceMinor,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
    accounts.id,
    accounts.workspace_id,
    accounts.name,
    accounts.type,
    accounts.currency,
    accounts.institution_name,
    accounts.archived_at,
    COALESCE(SUM(
        CASE
            WHEN transactions.status = 'posted' AND transactions.deleted_at IS NULL
                THEN transaction_entries.amount_minor
            ELSE 0
        END
    ), 0)::BIGINT AS balance_minor
FROM accounts
LEFT JOIN transaction_entries
    ON transaction_entries.workspace_id = accounts.workspace_id
   AND transaction_entries.account_id = accounts.id
LEFT JOIN transactions
    ON transactions.workspace_id = transaction_entries.workspace_id
   AND transactions.id = transaction_entries.transaction_id
WHERE accounts.workspace_id = $1
  AND ($2::BOOLEAN OR accounts.archived_at IS NULL)
GROUP BY accounts.id
ORDER BY accounts.archived_at NULLS FIRST, lower(accounts.name), accounts.id
`

type ListAccountsParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	IncludeArchived bool        `json:"include_archived"`
}

type ListAccountsRow struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Name            string             `json:"name"`
	Type            string             `json:"type"`
	Currency        string             `json:"currency"`
	InstitutionName pgtype.Text        `json:"institution_name"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	BalanceMinor    int64              `json:"balance_minor"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.WorkspaceID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.InstitutionName,
			&i.ArchivedAt,
			&i.BalanceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :execrows
UPDATE accounts
SET name = $1,
    type = $2,
    currency = $3,
    institution_name = $4,
    updated_at = now()
WHERE workspace_id = $5
  AND id = $6
`

type UpdateAccountParams struct {
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Currency        string      `json:"currency"`
	InstitutionName pgtype.Text `json:"institution_name"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.InstitutionName,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
