// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnalysisTotals = `-- name: GetAnalysisTotals :one

WITH transaction_totals AS (
    SELECT
        transactions.id,
        transactions.transaction_date,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE categories.kind = 'income'
        ), 0)::BIGINT AS income_signed_minor,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE categories.kind = 'expense'
        ), 0)::BIGINT AS expense_signed_minor
    FROM transaction_allocations
    JOIN transactions
        ON transactions.workspace_id = transaction_allocations.workspace_id
       AND transactions.id = transaction_allocations.transaction_id
    JOIN categories
        ON categories.workspace_id = transaction_allocations.workspace_id
       AND categories.id = transaction_allocations.category_id
    WHERE transaction_allocations.workspace_id = $1
      AND transactions.status = 'posted'
      AND transactions.deleted_at IS NULL
      AND transactions.transaction_date >= $2::DATE
      AND transactions.transaction_date <= $3::DATE
    GROUP BY transactions.id, transactions.transaction_date
),
windowed AS (
    SELECT
        transaction_totals.id, transaction_totals.transaction_date, transaction_totals.income_signed_minor, transaction_totals.expense_signed_minor,
        transaction_totals.transaction_date >= $4::DATE AS is_current
    FROM transaction_totals
)
SELECT
    COALESCE(SUM(income_signed_minor) FILTER (WHERE is_current), 0)::BIGINT
        AS income_signed_minor,
    COALESCE(SUM(expense_signed_minor) FILTER (WHERE is_current), 0)::BIGINT
        AS expense_signed_minor,
    COALESCE(SUM(income_signed_minor) FILTER (WHERE NOT is_current), 0)::BIGINT
        AS comparison_income_signed_minor,
    COALESCE(SUM(expense_signed_minor) FILTER (WHERE NOT is_current), 0)::BIGINT
        AS comparison_expense_signed_minor,
    COUNT(*) FILTER (WHERE is_current)::BIGINT AS transaction_count,
    COUNT(*) FILTER (WHERE is_current AND expense_signed_minor <> 0)::BIGINT
        AS spending_transaction_count,
    COALESCE(MIN(expense_signed_minor) FILTER (WHERE is_current), 0)::BIGINT
        AS smallest_expense_signed_minor,
    COUNT(DISTINCT transaction_date) FILTER (WHERE is_current AND expense_signed_minor <> 0)::BIGINT
        AS spending_day_count
FROM windowed
`

type GetAnalysisTotalsParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	ComparisonFromDate pgtype.Date `json:"comparison_from_date"`
	ToDate             pgtype.Date `json:"to_date"`
	FromDate           pgtype.Date `json:"from_date"`
}

type GetAnalysisTotalsRow struct {
	IncomeSignedMinor            int64 `json:"income_signed_minor"`
	ExpenseSignedMinor           int64 `json:"expense_signed_minor"`
	ComparisonIncomeSignedMinor  int64 `json:"comparison_income_signed_minor"`
	ComparisonExpenseSignedMinor int64 `json:"comparison_expense_signed_minor"`
	TransactionCount             int64 `json:"transaction_count"`
	SpendingTransactionCount     int64 `json:"spending_transaction_count"`
	SmallestExpenseSignedMinor   int64 `json:"smallest_expense_signed_minor"`
	SpendingDayCount             int64 `json:"spending_day_count"`
}

// Spending analysis reads only posted, non-deleted activity. Transfers carry no allocations,
// so allocation-derived aggregates exclude them by construction. Amounts keep their ledger
// sign here; the analytics domain converts them to reporting orientation.
func (q *Queries) GetAnalysisTotals(ctx context.Context, arg GetAnalysisTotalsParams) (GetAnalysisTotalsRow, error) {
	row := q.db.QueryRow(ctx, getAnalysisTotals,
		arg.WorkspaceID,
		arg.ComparisonFromDate,
		arg.ToDate,
		arg.FromDate,
	)
	var i GetAnalysisTotalsRow
	err := row.Scan(
		&i.IncomeSignedMinor,
		&i.ExpenseSignedMinor,
		&i.ComparisonIncomeSignedMinor,
		&i.ComparisonExpenseSignedMinor,
		&i.TransactionCount,
		&i.SpendingTransactionCount,
		&i.SmallestExpenseSignedMinor,
		&i.SpendingDayCount,
	)
	return i, err
}

const listAnalysisAccountActivity = `-- name: ListAnalysisAccountActivity :many
SELECT
    accounts.id,
    accounts.name,
    accounts.type,
    accounts.currency,
    accounts.archived_at,
    COALESCE(SUM(transaction_entries.base_amount_minor) FILTER (
        WHERE transaction_entries.base_amount_minor < 0
    ), 0)::BIGINT AS outflow_signed_minor,
    COALESCE(SUM(transaction_entries.base_amount_minor) FILTER (
        WHERE transaction_entries.base_amount_minor > 0
    ), 0)::BIGINT AS inflow_signed_minor,
    COUNT(DISTINCT transactions.id)::BIGINT AS transaction_count
FROM accounts
JOIN transaction_entries
    ON transaction_entries.workspace_id = accounts.workspace_id
   AND transaction_entries.account_id = accounts.id
JOIN transactions
    ON transactions.workspace_id = transaction_entries.workspace_id
   AND transactions.id = transaction_entries.transaction_id
WHERE accounts.workspace_id = $1
  AND transactions.status = 'posted'
  AND transactions.deleted_at IS NULL
  AND transactions.kind <> 'transfer'
  AND transactions.transaction_date >= $2::DATE
  AND transactions.transaction_date <= $3::DATE
GROUP BY accounts.id
HAVING COUNT(DISTINCT transactions.id) > 0
ORDER BY lower(accounts.name), accounts.id
`

type ListAnalysisAccountActivityParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
}

type ListAnalysisAccountActivityRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Type               string             `json:"type"`
	Currency           string             `json:"currency"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	OutflowSignedMinor int64              `json:"outflow_signed_minor"`
	InflowSignedMinor  int64              `json:"inflow_signed_minor"`
	TransactionCount   int64              `json:"transaction_count"`
}

// Entry-derived so it answers which account money moved through. Transfers are excluded so
// moving money between owned accounts never reads as spending.
func (q *Queries) ListAnalysisAccountActivity(ctx context.Context, arg ListAnalysisAccountActivityParams) ([]ListAnalysisAccountActivityRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisAccountActivity, arg.WorkspaceID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalysisAccountActivityRow{}
	for rows.Next() {
		var i ListAnalysisAccountActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.ArchivedAt,
			&i.OutflowSignedMinor,
			&i.InflowSignedMinor,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisBuckets = `-- name: ListAnalysisBuckets :many
WITH bucket_starts AS (
    SELECT generate_series(
        date_trunc($2::TEXT, $1::DATE::TIMESTAMP),
        date_trunc($2::TEXT, $3::DATE::TIMESTAMP),
        ('1 ' || $2::TEXT)::INTERVAL
    )::DATE AS bucket_anchor
),
activity AS (
    SELECT
        date_trunc(
            $2::TEXT, transactions.transaction_date::TIMESTAMP
        )::DATE AS bucket_anchor,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE categories.kind = 'income'
        ), 0)::BIGINT AS income_signed_minor,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE categories.kind = 'expense'
        ), 0)::BIGINT AS expense_signed_minor,
        COUNT(DISTINCT transactions.id)::BIGINT AS transaction_count
    FROM transaction_allocations
    JOIN transactions
        ON transactions.workspace_id = transaction_allocations.workspace_id
       AND transactions.id = transaction_allocations.transaction_id
    JOIN categories
        ON categories.workspace_id = transaction_allocations.workspace_id
       AND categories.id = transaction_allocations.category_id
    WHERE transaction_allocations.workspace_id = $4
      AND transactions.status = 'posted'
      AND transactions.deleted_at IS NULL
      AND transactions.transaction_date >= $1::DATE
      AND transactions.transaction_date <= $3::DATE
    GROUP BY 1
)
SELECT
    GREATEST(bucket_starts.bucket_anchor, $1::DATE)::DATE AS start_date,
    LEAST(
        (
            bucket_starts.bucket_anchor
            + ('1 ' || $2::TEXT)::INTERVAL
            - INTERVAL '1 day'
        )::DATE,
        $3::DATE
    )::DATE AS end_date,
    COALESCE(activity.income_signed_minor, 0)::BIGINT AS income_signed_minor,
    COALESCE(activity.expense_signed_minor, 0)::BIGINT AS expense_signed_minor,
    COALESCE(activity.transaction_count, 0)::BIGINT AS transaction_count
FROM bucket_starts
LEFT JOIN activity ON activity.bucket_anchor = bucket_starts.bucket_anchor
ORDER BY bucket_starts.bucket_anchor
`

type ListAnalysisBucketsParams struct {
	FromDate    pgtype.Date `json:"from_date"`
	Granularity string      `json:"granularity"`
	ToDate      pgtype.Date `json:"to_date"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type ListAnalysisBucketsRow struct {
	StartDate          pgtype.Date `json:"start_date"`
	EndDate            pgtype.Date `json:"end_date"`
	IncomeSignedMinor  int64       `json:"income_signed_minor"`
	ExpenseSignedMinor int64       `json:"expense_signed_minor"`
	TransactionCount   int64       `json:"transaction_count"`
}

func (q *Queries) ListAnalysisBuckets(ctx context.Context, arg ListAnalysisBucketsParams) ([]ListAnalysisBucketsRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisBuckets,
		arg.FromDate,
		arg.Granularity,
		arg.ToDate,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalysisBucketsRow{}
	for rows.Next() {
		var i ListAnalysisBucketsRow
		if err := rows.Scan(
			&i.StartDate,
			&i.EndDate,
			&i.IncomeSignedMinor,
			&i.ExpenseSignedMinor,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisCategoryBuckets = `-- name: ListAnalysisCategoryBuckets :many
SELECT
    transaction_allocations.category_id,
    date_trunc(
        $1::TEXT, transactions.transaction_date::TIMESTAMP
    )::DATE AS bucket_anchor,
    SUM(transaction_allocations.amount_base_minor)::BIGINT AS signed_minor
FROM transaction_allocations
JOIN transactions
    ON transactions.workspace_id = transaction_allocations.workspace_id
   AND transactions.id = transaction_allocations.transaction_id
WHERE transaction_allocations.workspace_id = $2
  AND transactions.status = 'posted'
  AND transactions.deleted_at IS NULL
  AND transactions.transaction_date >= $3::DATE
  AND transactions.transaction_date <= $4::DATE
GROUP BY 1, 2
HAVING SUM(transaction_allocations.amount_base_minor) <> 0
ORDER BY 1, 2
`

type ListAnalysisCategoryBucketsParams struct {
	Granularity string      `json:"granularity"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
}

type ListAnalysisCategoryBucketsRow struct {
	CategoryID   pgtype.UUID `json:"category_id"`
	BucketAnchor pgtype.Date `json:"bucket_anchor"`
	SignedMinor  int64       `json:"signed_minor"`
}

func (q *Queries) ListAnalysisCategoryBuckets(ctx context.Context, arg ListAnalysisCategoryBucketsParams) ([]ListAnalysisCategoryBucketsRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisCategoryBuckets,
		arg.Granularity,
		arg.WorkspaceID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalysisCategoryBucketsRow{}
	for rows.Next() {
		var i ListAnalysisCategoryBucketsRow
		if err := rows.Scan(&i.CategoryID, &i.BucketAnchor, &i.SignedMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisCategoryTotals = `-- name: ListAnalysisCategoryTotals :many
WITH RECURSIVE category_ancestors AS (
    SELECT categories.id AS descendant_id, categories.id AS ancestor_id
    FROM categories
    WHERE categories.workspace_id = $1

    UNION ALL

    SELECT category_ancestors.descendant_id, parent.id AS ancestor_id
    FROM category_ancestors
    JOIN categories AS child
      ON child.workspace_id = $1
     AND child.id = category_ancestors.ancestor_id
    JOIN categories AS parent
      ON parent.workspace_id = child.workspace_id
     AND parent.id = child.parent_id
),
direct_activity AS (
    SELECT
        categories.id,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE transactions.status = 'posted'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $2::DATE
              AND transactions.transaction_date <= $3::DATE
        ), 0)::BIGINT AS direct_signed_minor,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE transactions.status = 'posted'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $4::DATE
              AND transactions.transaction_date < $2::DATE
        ), 0)::BIGINT AS comparison_direct_signed_minor,
        COUNT(DISTINCT transactions.id) FILTER (
            WHERE transactions.status = 'posted'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $2::DATE
              AND transactions.transaction_date <= $3::DATE
        )::BIGINT AS transaction_count,
        COALESCE(MIN(transaction_allocations.amount_base_minor) FILTER (
            WHERE transactions.status = 'posted'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $2::DATE
              AND transactions.transaction_date <= $3::DATE
        ), 0)::BIGINT AS smallest_signed_minor,
        COALESCE(MAX(transaction_allocations.amount_base_minor) FILTER (
            WHERE transactions.status = 'posted'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $2::DATE
              AND transactions.transaction_date <= $3::DATE
        ), 0)::BIGINT AS largest_signed_minor,
        MIN(transactions.transaction_date) FILTER (
            WHERE transactions.status = 'posted'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $2::DATE
              AND transactions.transaction_date <= $3::DATE
        )::DATE AS first_date,
        MAX(transactions.transaction_date) FILTER (
            WHERE transactions.status = 'posted'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $2::DATE
              AND transactions.transaction_date <= $3::DATE
        )::DATE AS last_date
    FROM categories
    LEFT JOIN transaction_allocations
      ON transaction_allocations.workspace_id = categories.workspace_id
     AND transaction_allocations.category_id = categories.id
    LEFT JOIN transactions
      ON transactions.workspace_id = transaction_allocations.workspace_id
     AND transactions.id = transaction_allocations.transaction_id
    WHERE categories.workspace_id = $1
    GROUP BY categories.id
),
rolled_activity AS (
    SELECT
        category_ancestors.ancestor_id AS id,
        SUM(direct_activity.direct_signed_minor)::BIGINT AS rolled_signed_minor,
        SUM(direct_activity.comparison_direct_signed_minor)::BIGINT
            AS comparison_rolled_signed_minor,
        SUM(direct_activity.transaction_count)::BIGINT AS rolled_transaction_count
    FROM category_ancestors
    JOIN direct_activity
      ON direct_activity.id = category_ancestors.descendant_id
    GROUP BY category_ancestors.ancestor_id
)
SELECT
    categories.id,
    categories.parent_id,
    categories.name,
    categories.kind,
    categories.system_key,
    categories.predefined_key,
    categories.icon,
    categories.icon_type,
    categories.icon_value,
    categories.color_key,
    categories.archived_at,
    direct_activity.direct_signed_minor,
    direct_activity.comparison_direct_signed_minor,
    direct_activity.transaction_count,
    direct_activity.smallest_signed_minor,
    direct_activity.largest_signed_minor,
    direct_activity.first_date,
    direct_activity.last_date,
    rolled_activity.rolled_signed_minor,
    rolled_activity.comparison_rolled_signed_minor,
    rolled_activity.rolled_transaction_count
FROM categories
JOIN direct_activity ON direct_activity.id = categories.id
JOIN rolled_activity ON rolled_activity.id = categories.id
WHERE categories.workspace_id = $1
ORDER BY categories.kind, categories.parent_id NULLS FIRST, lower(categories.name), categories.id
`

type ListAnalysisCategoryTotalsParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	FromDate           pgtype.Date `json:"from_date"`
	ToDate             pgtype.Date `json:"to_date"`
	ComparisonFromDate pgtype.Date `json:"comparison_from_date"`
}

type ListAnalysisCategoryTotalsRow struct {
	ID                          pgtype.UUID        `json:"id"`
	ParentID                    pgtype.UUID        `json:"parent_id"`
	Name                        string             `json:"name"`
	Kind                        string             `json:"kind"`
	SystemKey                   pgtype.Text        `json:"system_key"`
	PredefinedKey               pgtype.Text        `json:"predefined_key"`
	Icon                        pgtype.Text        `json:"icon"`
	IconType                    string             `json:"icon_type"`
	IconValue                   string             `json:"icon_value"`
	ColorKey                    string             `json:"color_key"`
	ArchivedAt                  pgtype.Timestamptz `json:"archived_at"`
	DirectSignedMinor           int64              `json:"direct_signed_minor"`
	ComparisonDirectSignedMinor int64              `json:"comparison_direct_signed_minor"`
	TransactionCount            int64              `json:"transaction_count"`
	SmallestSignedMinor         int64              `json:"smallest_signed_minor"`
	LargestSignedMinor          int64              `json:"largest_signed_minor"`
	FirstDate                   pgtype.Date        `json:"first_date"`
	LastDate                    pgtype.Date        `json:"last_date"`
	RolledSignedMinor           int64              `json:"rolled_signed_minor"`
	ComparisonRolledSignedMinor int64              `json:"comparison_rolled_signed_minor"`
	RolledTransactionCount      int64              `json:"rolled_transaction_count"`
}

func (q *Queries) ListAnalysisCategoryTotals(ctx context.Context, arg ListAnalysisCategoryTotalsParams) ([]ListAnalysisCategoryTotalsRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisCategoryTotals,
		arg.WorkspaceID,
		arg.FromDate,
		arg.ToDate,
		arg.ComparisonFromDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalysisCategoryTotalsRow{}
	for rows.Next() {
		var i ListAnalysisCategoryTotalsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.SystemKey,
			&i.PredefinedKey,
			&i.Icon,
			&i.IconType,
			&i.IconValue,
			&i.ColorKey,
			&i.ArchivedAt,
			&i.DirectSignedMinor,
			&i.ComparisonDirectSignedMinor,
			&i.TransactionCount,
			&i.SmallestSignedMinor,
			&i.LargestSignedMinor,
			&i.FirstDate,
			&i.LastDate,
			&i.RolledSignedMinor,
			&i.ComparisonRolledSignedMinor,
			&i.RolledTransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisDays = `-- name: ListAnalysisDays :many
SELECT
    transactions.transaction_date AS activity_date,
    COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
        WHERE categories.kind = 'income'
    ), 0)::BIGINT AS income_signed_minor,
    COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
        WHERE categories.kind = 'expense'
    ), 0)::BIGINT AS expense_signed_minor,
    COUNT(DISTINCT transactions.id)::BIGINT AS transaction_count
FROM transaction_allocations
JOIN transactions
    ON transactions.workspace_id = transaction_allocations.workspace_id
   AND transactions.id = transaction_allocations.transaction_id
JOIN categories
    ON categories.workspace_id = transaction_allocations.workspace_id
   AND categories.id = transaction_allocations.category_id
WHERE transaction_allocations.workspace_id = $1
  AND transactions.status = 'posted'
  AND transactions.deleted_at IS NULL
  AND transactions.transaction_date >= $2::DATE
  AND transactions.transaction_date <= $3::DATE
GROUP BY 1
ORDER BY 1
`

type ListAnalysisDaysParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
}

type ListAnalysisDaysRow struct {
	ActivityDate       pgtype.Date `json:"activity_date"`
	IncomeSignedMinor  int64       `json:"income_signed_minor"`
	ExpenseSignedMinor int64       `json:"expense_signed_minor"`
	TransactionCount   int64       `json:"transaction_count"`
}

func (q *Queries) ListAnalysisDays(ctx context.Context, arg ListAnalysisDaysParams) ([]ListAnalysisDaysRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisDays, arg.WorkspaceID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalysisDaysRow{}
	for rows.Next() {
		var i ListAnalysisDaysRow
		if err := rows.Scan(
			&i.ActivityDate,
			&i.IncomeSignedMinor,
			&i.ExpenseSignedMinor,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisPayees = `-- name: ListAnalysisPayees :many
SELECT
    btrim(transactions.payee) AS payee,
    COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
        WHERE categories.kind = 'expense'
    ), 0)::BIGINT AS expense_signed_minor,
    COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
        WHERE categories.kind = 'income'
    ), 0)::BIGINT AS income_signed_minor,
    COUNT(DISTINCT transactions.id)::BIGINT AS transaction_count,
    MIN(transactions.transaction_date)::DATE AS first_date,
    MAX(transactions.transaction_date)::DATE AS last_date
FROM transaction_allocations
JOIN transactions
    ON transactions.workspace_id = transaction_allocations.workspace_id
   AND transactions.id = transaction_allocations.transaction_id
JOIN categories
    ON categories.workspace_id = transaction_allocations.workspace_id
   AND categories.id = transaction_allocations.category_id
WHERE transaction_allocations.workspace_id = $1
  AND transactions.status = 'posted'
  AND transactions.deleted_at IS NULL
  AND transactions.transaction_date >= $2::DATE
  AND transactions.transaction_date <= $3::DATE
  AND btrim(COALESCE(transactions.payee, '')) <> ''
GROUP BY 1
ORDER BY 2, 4 DESC
LIMIT $4
`

type ListAnalysisPayeesParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
	RowLimit    int32       `json:"row_limit"`
}

type ListAnalysisPayeesRow struct {
	Payee              string      `json:"payee"`
	ExpenseSignedMinor int64       `json:"expense_signed_minor"`
	IncomeSignedMinor  int64       `json:"income_signed_minor"`
	TransactionCount   int64       `json:"transaction_count"`
	FirstDate          pgtype.Date `json:"first_date"`
	LastDate           pgtype.Date `json:"last_date"`
}

func (q *Queries) ListAnalysisPayees(ctx context.Context, arg ListAnalysisPayeesParams) ([]ListAnalysisPayeesRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisPayees,
		arg.WorkspaceID,
		arg.FromDate,
		arg.ToDate,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalysisPayeesRow{}
	for rows.Next() {
		var i ListAnalysisPayeesRow
		if err := rows.Scan(
			&i.Payee,
			&i.ExpenseSignedMinor,
			&i.IncomeSignedMinor,
			&i.TransactionCount,
			&i.FirstDate,
			&i.LastDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisWeekdays = `-- name: ListAnalysisWeekdays :many
SELECT
    EXTRACT(ISODOW FROM transactions.transaction_date)::SMALLINT AS weekday,
    COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
        WHERE categories.kind = 'income'
    ), 0)::BIGINT AS income_signed_minor,
    COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
        WHERE categories.kind = 'expense'
    ), 0)::BIGINT AS expense_signed_minor,
    COUNT(DISTINCT transactions.id)::BIGINT AS transaction_count
FROM transaction_allocations
JOIN transactions
    ON transactions.workspace_id = transaction_allocations.workspace_id
   AND transactions.id = transaction_allocations.transaction_id
JOIN categories
    ON categories.workspace_id = transaction_allocations.workspace_id
   AND categories.id = transaction_allocations.category_id
WHERE transaction_allocations.workspace_id = $1
  AND transactions.status = 'posted'
  AND transactions.deleted_at IS NULL
  AND transactions.transaction_date >= $2::DATE
  AND transactions.transaction_date <= $3::DATE
GROUP BY 1
ORDER BY 1
`

type ListAnalysisWeekdaysParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
}

type ListAnalysisWeekdaysRow struct {
	Weekday            int16 `json:"weekday"`
	IncomeSignedMinor  int64 `json:"income_signed_minor"`
	ExpenseSignedMinor int64 `json:"expense_signed_minor"`
	TransactionCount   int64 `json:"transaction_count"`
}

func (q *Queries) ListAnalysisWeekdays(ctx context.Context, arg ListAnalysisWeekdaysParams) ([]ListAnalysisWeekdaysRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisWeekdays, arg.WorkspaceID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalysisWeekdaysRow{}
	for rows.Next() {
		var i ListAnalysisWeekdaysRow
		if err := rows.Scan(
			&i.Weekday,
			&i.IncomeSignedMinor,
			&i.ExpenseSignedMinor,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
