// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, transport, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	Transport string             `json:"transport"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Transport,
		arg.ExpiresAt,
	)
	return err
}

const createSystemCategory = `-- name: CreateSystemCategory :exec
INSERT INTO categories (id, workspace_id, name, kind, system_key)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSystemCategoryParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Kind        string      `json:"kind"`
	SystemKey   pgtype.Text `json:"system_key"`
}

func (q *Queries) CreateSystemCategory(ctx context.Context, arg CreateSystemCategoryParams) error {
	_, err := q.db.Exec(ctx, createSystemCategory,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Kind,
		arg.SystemKey,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, display_name
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  string      `json:"display_name"`
}

type CreateUserRow struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, base_currency, timezone, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, base_currency, timezone
`

type CreateWorkspaceParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	BaseCurrency string      `json:"base_currency"`
	Timezone     string      `json:"timezone"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

type CreateWorkspaceRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	BaseCurrency string      `json:"base_currency"`
	Timezone     string      `json:"timezone"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (CreateWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.BaseCurrency,
		arg.Timezone,
		arg.CreatedBy,
	)
	var i CreateWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.Timezone,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = $1
  AND user_id = $2
`

type DeleteSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    sessions.id AS session_id,
    sessions.user_id,
    sessions.transport,
    users.email,
    users.display_name
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	SessionID   pgtype.UUID `json:"session_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Transport   string      `json:"transport"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Transport,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name
FROM users
WHERE lower(email) = lower($1)
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  string      `json:"display_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
	)
	return i, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT
    workspaces.id,
    workspaces.name,
    workspaces.base_currency,
    workspaces.timezone,
    workspace_members.role
FROM workspace_members
JOIN workspaces ON workspaces.id = workspace_members.workspace_id
WHERE workspace_members.user_id = $1
  AND workspace_members.removed_at IS NULL
ORDER BY workspace_members.joined_at, workspaces.id
`

type ListWorkspacesByUserRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	BaseCurrency string      `json:"base_currency"`
	Timezone     string      `json:"timezone"`
	Role         string      `json:"role"`
}

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID pgtype.UUID) ([]ListWorkspacesByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesByUserRow{}
	for rows.Next() {
		var i ListWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseCurrency,
			&i.Timezone,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
