// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOmittedMonthlyBudgetItems = `-- name: DeleteOmittedMonthlyBudgetItems :exec
DELETE FROM budget_items
WHERE workspace_id = $1
  AND budget_id = $2
  AND NOT (category_id = ANY($3::UUID[]))
`

type DeleteOmittedMonthlyBudgetItemsParams struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	BudgetID    pgtype.UUID   `json:"budget_id"`
	CategoryIds []pgtype.UUID `json:"category_ids"`
}

func (q *Queries) DeleteOmittedMonthlyBudgetItems(ctx context.Context, arg DeleteOmittedMonthlyBudgetItemsParams) error {
	_, err := q.db.Exec(ctx, deleteOmittedMonthlyBudgetItems, arg.WorkspaceID, arg.BudgetID, arg.CategoryIds)
	return err
}

const getBudgetWorkspaceSettings = `-- name: GetBudgetWorkspaceSettings :one
SELECT base_currency, timezone
FROM workspaces
WHERE id = $1
`

type GetBudgetWorkspaceSettingsRow struct {
	BaseCurrency string `json:"base_currency"`
	Timezone     string `json:"timezone"`
}

func (q *Queries) GetBudgetWorkspaceSettings(ctx context.Context, id pgtype.UUID) (GetBudgetWorkspaceSettingsRow, error) {
	row := q.db.QueryRow(ctx, getBudgetWorkspaceSettings, id)
	var i GetBudgetWorkspaceSettingsRow
	err := row.Scan(&i.BaseCurrency, &i.Timezone)
	return i, err
}

const getMonthlyBudget = `-- name: GetMonthlyBudget :one
SELECT
    budgets.id,
    budgets.workspace_id,
    budgets.name,
    budgets.starts_on,
    workspaces.timezone,
    workspaces.base_currency,
    budgets.created_at,
    budgets.updated_at
FROM budgets
JOIN workspaces ON workspaces.id = budgets.workspace_id
WHERE budgets.workspace_id = $1
  AND budgets.starts_on = $2::DATE
`

type GetMonthlyBudgetParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StartsOn    pgtype.Date `json:"starts_on"`
}

type GetMonthlyBudgetRow struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Name         string             `json:"name"`
	StartsOn     pgtype.Date        `json:"starts_on"`
	Timezone     string             `json:"timezone"`
	BaseCurrency string             `json:"base_currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMonthlyBudget(ctx context.Context, arg GetMonthlyBudgetParams) (GetMonthlyBudgetRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyBudget, arg.WorkspaceID, arg.StartsOn)
	var i GetMonthlyBudgetRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.StartsOn,
		&i.Timezone,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetCategoryRules = `-- name: ListBudgetCategoryRules :many
SELECT
    categories.id,
    categories.parent_id,
    categories.kind,
    categories.archived_at,
    EXISTS (
        SELECT 1
        FROM budgets
        JOIN budget_items
          ON budget_items.workspace_id = budgets.workspace_id
         AND budget_items.budget_id = budgets.id
        WHERE budgets.workspace_id = categories.workspace_id
          AND budgets.starts_on = $1::DATE
          AND budget_items.category_id = categories.id
    ) AS already_budgeted
FROM categories
WHERE categories.workspace_id = $2
ORDER BY categories.id
`

type ListBudgetCategoryRulesParams struct {
	StartsOn    pgtype.Date `json:"starts_on"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type ListBudgetCategoryRulesRow struct {
	ID              pgtype.UUID        `json:"id"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	Kind            string             `json:"kind"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	AlreadyBudgeted bool               `json:"already_budgeted"`
}

func (q *Queries) ListBudgetCategoryRules(ctx context.Context, arg ListBudgetCategoryRulesParams) ([]ListBudgetCategoryRulesRow, error) {
	rows, err := q.db.Query(ctx, listBudgetCategoryRules, arg.StartsOn, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetCategoryRulesRow{}
	for rows.Next() {
		var i ListBudgetCategoryRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.ArchivedAt,
			&i.AlreadyBudgeted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyBudgetItems = `-- name: ListMonthlyBudgetItems :many
WITH RECURSIVE category_descendants AS (
    SELECT
        budget_items.id AS budget_item_id,
        budget_items.category_id AS descendant_id
    FROM budget_items
    WHERE budget_items.workspace_id = $1
      AND budget_items.budget_id = $2

    UNION ALL

    SELECT
        category_descendants.budget_item_id,
        child.id AS descendant_id
    FROM category_descendants
    JOIN categories AS child
      ON child.workspace_id = $1
     AND child.parent_id = category_descendants.descendant_id
),
item_usage AS (
    SELECT
        category_descendants.budget_item_id,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE transactions.id IS NOT NULL
        ), 0)::BIGINT
            AS signed_allocation_base_minor
    FROM category_descendants
    LEFT JOIN transaction_allocations
      ON transaction_allocations.workspace_id = $1
     AND transaction_allocations.category_id = category_descendants.descendant_id
    LEFT JOIN transactions
      ON transactions.workspace_id = transaction_allocations.workspace_id
     AND transactions.id = transaction_allocations.transaction_id
     AND transactions.status = 'posted'
     AND transactions.deleted_at IS NULL
     AND transactions.transaction_date >= $3::DATE
     AND transactions.transaction_date < ($3::DATE + INTERVAL '1 month')
    GROUP BY category_descendants.budget_item_id
)
SELECT
    budget_items.id,
    budget_items.category_id,
    categories.name AS category_name,
    categories.icon AS category_icon,
    categories.archived_at AS category_archived_at,
    budget_items.amount_base_minor AS planned_base_minor,
    item_usage.signed_allocation_base_minor
FROM budget_items
JOIN categories
  ON categories.workspace_id = budget_items.workspace_id
 AND categories.id = budget_items.category_id
JOIN item_usage ON item_usage.budget_item_id = budget_items.id
WHERE budget_items.workspace_id = $1
  AND budget_items.budget_id = $2
ORDER BY lower(categories.name), budget_items.id
`

type ListMonthlyBudgetItemsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	BudgetID    pgtype.UUID `json:"budget_id"`
	StartsOn    pgtype.Date `json:"starts_on"`
}

type ListMonthlyBudgetItemsRow struct {
	ID                        pgtype.UUID        `json:"id"`
	CategoryID                pgtype.UUID        `json:"category_id"`
	CategoryName              string             `json:"category_name"`
	CategoryIcon              pgtype.Text        `json:"category_icon"`
	CategoryArchivedAt        pgtype.Timestamptz `json:"category_archived_at"`
	PlannedBaseMinor          int64              `json:"planned_base_minor"`
	SignedAllocationBaseMinor int64              `json:"signed_allocation_base_minor"`
}

func (q *Queries) ListMonthlyBudgetItems(ctx context.Context, arg ListMonthlyBudgetItemsParams) ([]ListMonthlyBudgetItemsRow, error) {
	rows, err := q.db.Query(ctx, listMonthlyBudgetItems, arg.WorkspaceID, arg.BudgetID, arg.StartsOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthlyBudgetItemsRow{}
	for rows.Next() {
		var i ListMonthlyBudgetItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryArchivedAt,
			&i.PlannedBaseMinor,
			&i.SignedAllocationBaseMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonthlyBudget = `-- name: UpsertMonthlyBudget :one
INSERT INTO budgets (
    id, workspace_id, name, period, starts_on, rollover, active
) VALUES (
    $1, $2, $3, 'monthly',
    $4, false, true
)
ON CONFLICT (workspace_id, starts_on) DO UPDATE
SET name = EXCLUDED.name,
    updated_at = now()
RETURNING id
`

type UpsertMonthlyBudgetParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	StartsOn    pgtype.Date `json:"starts_on"`
}

func (q *Queries) UpsertMonthlyBudget(ctx context.Context, arg UpsertMonthlyBudgetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMonthlyBudget,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.StartsOn,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertMonthlyBudgetItem = `-- name: UpsertMonthlyBudgetItem :one
INSERT INTO budget_items (
    id, workspace_id, budget_id, category_id, amount_base_minor
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (budget_id, category_id) DO UPDATE
SET amount_base_minor = EXCLUDED.amount_base_minor
RETURNING id
`

type UpsertMonthlyBudgetItemParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	BudgetID        pgtype.UUID `json:"budget_id"`
	CategoryID      pgtype.UUID `json:"category_id"`
	AmountBaseMinor int64       `json:"amount_base_minor"`
}

func (q *Queries) UpsertMonthlyBudgetItem(ctx context.Context, arg UpsertMonthlyBudgetItemParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMonthlyBudgetItem,
		arg.ID,
		arg.WorkspaceID,
		arg.BudgetID,
		arg.CategoryID,
		arg.AmountBaseMinor,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
