// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCategory = `-- name: ArchiveCategory :execrows
UPDATE categories
SET archived_at = COALESCE(archived_at, now()),
    updated_at = CASE WHEN archived_at IS NULL THEN now() ELSE updated_at END
WHERE workspace_id = $1
  AND id = $2
`

type ArchiveCategoryParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCategory, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const categoryHasAllocations = `-- name: CategoryHasAllocations :one
SELECT EXISTS (
    SELECT 1
    FROM transaction_allocations
    WHERE workspace_id = $1
      AND category_id = $2
)
`

type CategoryHasAllocationsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	CategoryID  pgtype.UUID `json:"category_id"`
}

func (q *Queries) CategoryHasAllocations(ctx context.Context, arg CategoryHasAllocationsParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryHasAllocations, arg.WorkspaceID, arg.CategoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryHasAnyChildren = `-- name: CategoryHasAnyChildren :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE workspace_id = $1
      AND parent_id = $2
)
`

type CategoryHasAnyChildrenParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CategoryHasAnyChildren(ctx context.Context, arg CategoryHasAnyChildrenParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryHasAnyChildren, arg.WorkspaceID, arg.ParentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryHasChildren = `-- name: CategoryHasChildren :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE workspace_id = $1
      AND parent_id = $2
      AND archived_at IS NULL
)
`

type CategoryHasChildrenParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CategoryHasChildren(ctx context.Context, arg CategoryHasChildrenParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryHasChildren, arg.WorkspaceID, arg.ParentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (
    id, workspace_id, parent_id, name, kind, icon
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateCategoryParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Kind        string      `json:"kind"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.Exec(ctx, createCategory,
		arg.ID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Kind,
		arg.Icon,
	)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT
    id,
    workspace_id,
    parent_id,
    name,
    kind,
    system_key,
    icon,
    archived_at
FROM categories
WHERE workspace_id = $1
  AND id = $2
`

type GetCategoryParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetCategoryRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	SystemKey   pgtype.Text        `json:"system_key"`
	Icon        pgtype.Text        `json:"icon"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.WorkspaceID, arg.ID)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.SystemKey,
		&i.Icon,
		&i.ArchivedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    workspace_id,
    parent_id,
    name,
    kind,
    system_key,
    icon,
    archived_at
FROM categories
WHERE workspace_id = $1
  AND ($2::BOOLEAN OR archived_at IS NULL)
ORDER BY kind, parent_id NULLS FIRST, lower(name), id
`

type ListCategoriesParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	IncludeArchived bool        `json:"include_archived"`
}

type ListCategoriesRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	SystemKey   pgtype.Text        `json:"system_key"`
	Icon        pgtype.Text        `json:"icon"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.WorkspaceID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.SystemKey,
			&i.Icon,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE categories
SET parent_id = $1,
    name = $2,
    kind = $3,
    icon = $4,
    updated_at = now()
WHERE workspace_id = $5
  AND id = $6
`

type UpdateCategoryParams struct {
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Kind        string      `json:"kind"`
	Icon        pgtype.Text `json:"icon"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategory,
		arg.ParentID,
		arg.Name,
		arg.Kind,
		arg.Icon,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
