// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaboration.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptWorkspaceInvitation = `-- name: AcceptWorkspaceInvitation :execrows
UPDATE workspace_invitations
SET accepted_at = $3,
    accepted_by = $4
WHERE id = $1
  AND workspace_id = $2
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > $3
`

type AcceptWorkspaceInvitationParams struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	AcceptedBy  pgtype.UUID        `json:"accepted_by"`
}

func (q *Queries) AcceptWorkspaceInvitation(ctx context.Context, arg AcceptWorkspaceInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptWorkspaceInvitation,
		arg.ID,
		arg.WorkspaceID,
		arg.AcceptedAt,
		arg.AcceptedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activateWorkspaceMembership = `-- name: ActivateWorkspaceMembership :one
INSERT INTO workspace_members (workspace_id, user_id, role, joined_at, removed_at)
VALUES ($1, $2, $3, $4, NULL)
ON CONFLICT (workspace_id, user_id) DO UPDATE
SET role = EXCLUDED.role,
    joined_at = EXCLUDED.joined_at,
    removed_at = NULL
RETURNING role, joined_at
`

type ActivateWorkspaceMembershipParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

type ActivateWorkspaceMembershipRow struct {
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ActivateWorkspaceMembership(ctx context.Context, arg ActivateWorkspaceMembershipParams) (ActivateWorkspaceMembershipRow, error) {
	row := q.db.QueryRow(ctx, activateWorkspaceMembership,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	var i ActivateWorkspaceMembershipRow
	err := row.Scan(&i.Role, &i.JoinedAt)
	return i, err
}

const countActiveWorkspaceOwners = `-- name: CountActiveWorkspaceOwners :one
SELECT count(*)
FROM workspace_members
WHERE workspace_id = $1
  AND role = 'owner'
  AND removed_at IS NULL
`

func (q *Queries) CountActiveWorkspaceOwners(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkspaceOwners, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspaceInvitation = `-- name: CreateWorkspaceInvitation :one
INSERT INTO workspace_invitations (
    id, workspace_id, email, role, token_hash, invited_by, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, email, role, invited_by, expires_at, created_at
`

type CreateWorkspaceInvitationParams struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	TokenHash   []byte             `json:"token_hash"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type CreateWorkspaceInvitationRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWorkspaceInvitation(ctx context.Context, arg CreateWorkspaceInvitationParams) (CreateWorkspaceInvitationRow, error) {
	row := q.db.QueryRow(ctx, createWorkspaceInvitation,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i CreateWorkspaceInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAcceptedWorkspaceSummary = `-- name: GetAcceptedWorkspaceSummary :one
SELECT
    workspaces.id,
    workspaces.name,
    workspaces.base_currency,
    workspaces.timezone,
    workspace_members.role
FROM workspaces
JOIN workspace_members ON workspace_members.workspace_id = workspaces.id
WHERE workspaces.id = $1
  AND workspace_members.user_id = $2
  AND workspace_members.removed_at IS NULL
`

type GetAcceptedWorkspaceSummaryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetAcceptedWorkspaceSummaryRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	BaseCurrency string      `json:"base_currency"`
	Timezone     string      `json:"timezone"`
	Role         string      `json:"role"`
}

func (q *Queries) GetAcceptedWorkspaceSummary(ctx context.Context, arg GetAcceptedWorkspaceSummaryParams) (GetAcceptedWorkspaceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAcceptedWorkspaceSummary, arg.ID, arg.UserID)
	var i GetAcceptedWorkspaceSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.Timezone,
		&i.Role,
	)
	return i, err
}

const getActiveWorkspaceMember = `-- name: GetActiveWorkspaceMember :one
SELECT
    workspace_members.user_id,
    users.email,
    users.display_name,
    workspace_members.role,
    workspace_members.joined_at
FROM workspace_members
JOIN users ON users.id = workspace_members.user_id
WHERE workspace_members.workspace_id = $1
  AND workspace_members.user_id = $2
  AND workspace_members.removed_at IS NULL
`

type GetActiveWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

type GetActiveWorkspaceMemberRow struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetActiveWorkspaceMember(ctx context.Context, arg GetActiveWorkspaceMemberParams) (GetActiveWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, getActiveWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i GetActiveWorkspaceMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getActiveWorkspaceMemberByEmail = `-- name: GetActiveWorkspaceMemberByEmail :one
SELECT workspace_members.user_id
FROM workspace_members
JOIN users ON users.id = workspace_members.user_id
WHERE workspace_members.workspace_id = $1
  AND lower(users.email) = lower($2)
  AND workspace_members.removed_at IS NULL
`

type GetActiveWorkspaceMemberByEmailParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Lower       string      `json:"lower"`
}

func (q *Queries) GetActiveWorkspaceMemberByEmail(ctx context.Context, arg GetActiveWorkspaceMemberByEmailParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveWorkspaceMemberByEmail, arg.WorkspaceID, arg.Lower)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getPendingWorkspaceInvitation = `-- name: GetPendingWorkspaceInvitation :one
SELECT
    workspace_invitations.id,
    workspace_invitations.workspace_id,
    workspace_invitations.email,
    workspace_invitations.role,
    workspace_invitations.invited_by,
    users.display_name AS inviter_display_name,
    workspace_invitations.expires_at,
    workspace_invitations.created_at
FROM workspace_invitations
JOIN users ON users.id = workspace_invitations.invited_by
WHERE workspace_invitations.workspace_id = $1
  AND workspace_invitations.id = $2
  AND workspace_invitations.accepted_at IS NULL
  AND workspace_invitations.revoked_at IS NULL
  AND workspace_invitations.expires_at > $3
`

type GetPendingWorkspaceInvitationParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type GetPendingWorkspaceInvitationRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Email              string             `json:"email"`
	Role               string             `json:"role"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	InviterDisplayName string             `json:"inviter_display_name"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPendingWorkspaceInvitation(ctx context.Context, arg GetPendingWorkspaceInvitationParams) (GetPendingWorkspaceInvitationRow, error) {
	row := q.db.QueryRow(ctx, getPendingWorkspaceInvitation, arg.WorkspaceID, arg.ID, arg.ExpiresAt)
	var i GetPendingWorkspaceInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.InviterDisplayName,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceInvitationByTokenHash = `-- name: GetWorkspaceInvitationByTokenHash :one
SELECT
    id,
    workspace_id,
    email,
    role,
    invited_by,
    expires_at,
    accepted_at,
    accepted_by,
    revoked_at,
    created_at
FROM workspace_invitations
WHERE token_hash = $1
`

type GetWorkspaceInvitationByTokenHashRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	AcceptedBy  pgtype.UUID        `json:"accepted_by"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetWorkspaceInvitationByTokenHash(ctx context.Context, tokenHash []byte) (GetWorkspaceInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitationByTokenHash, tokenHash)
	var i GetWorkspaceInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceInvitationByTokenHashForUpdate = `-- name: GetWorkspaceInvitationByTokenHashForUpdate :one
SELECT
    id,
    workspace_id,
    email,
    role,
    invited_by,
    expires_at,
    accepted_at,
    accepted_by,
    revoked_at,
    created_at
FROM workspace_invitations
WHERE token_hash = $1
FOR UPDATE
`

type GetWorkspaceInvitationByTokenHashForUpdateRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	AcceptedBy  pgtype.UUID        `json:"accepted_by"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetWorkspaceInvitationByTokenHashForUpdate(ctx context.Context, tokenHash []byte) (GetWorkspaceInvitationByTokenHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitationByTokenHashForUpdate, tokenHash)
	var i GetWorkspaceInvitationByTokenHashForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMembershipForUpdate = `-- name: GetWorkspaceMembershipForUpdate :one
SELECT role, joined_at, removed_at
FROM workspace_members
WHERE workspace_id = $1
  AND user_id = $2
FOR UPDATE
`

type GetWorkspaceMembershipForUpdateParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

type GetWorkspaceMembershipForUpdateRow struct {
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	RemovedAt pgtype.Timestamptz `json:"removed_at"`
}

func (q *Queries) GetWorkspaceMembershipForUpdate(ctx context.Context, arg GetWorkspaceMembershipForUpdateParams) (GetWorkspaceMembershipForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMembershipForUpdate, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMembershipForUpdateRow
	err := row.Scan(&i.Role, &i.JoinedAt, &i.RemovedAt)
	return i, err
}

const listActiveWorkspaceMembers = `-- name: ListActiveWorkspaceMembers :many
SELECT
    workspace_members.user_id,
    users.email,
    users.display_name,
    workspace_members.role,
    workspace_members.joined_at
FROM workspace_members
JOIN users ON users.id = workspace_members.user_id
WHERE workspace_members.workspace_id = $1
  AND workspace_members.removed_at IS NULL
ORDER BY
    CASE workspace_members.role
        WHEN 'owner' THEN 1
        WHEN 'admin' THEN 2
        WHEN 'member' THEN 3
        ELSE 4
    END,
    lower(users.display_name),
    workspace_members.user_id
`

type ListActiveWorkspaceMembersRow struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListActiveWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]ListActiveWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveWorkspaceMembersRow{}
	for rows.Next() {
		var i ListActiveWorkspaceMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWorkspaceInvitations = `-- name: ListPendingWorkspaceInvitations :many
SELECT
    workspace_invitations.id,
    workspace_invitations.workspace_id,
    workspace_invitations.email,
    workspace_invitations.role,
    workspace_invitations.invited_by,
    users.display_name AS inviter_display_name,
    workspace_invitations.expires_at,
    workspace_invitations.created_at
FROM workspace_invitations
JOIN users ON users.id = workspace_invitations.invited_by
WHERE workspace_invitations.workspace_id = $1
  AND workspace_invitations.accepted_at IS NULL
  AND workspace_invitations.revoked_at IS NULL
  AND workspace_invitations.expires_at > $2
ORDER BY workspace_invitations.created_at DESC, workspace_invitations.id DESC
`

type ListPendingWorkspaceInvitationsParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type ListPendingWorkspaceInvitationsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Email              string             `json:"email"`
	Role               string             `json:"role"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	InviterDisplayName string             `json:"inviter_display_name"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingWorkspaceInvitations(ctx context.Context, arg ListPendingWorkspaceInvitationsParams) ([]ListPendingWorkspaceInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingWorkspaceInvitations, arg.WorkspaceID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingWorkspaceInvitationsRow{}
	for rows.Next() {
		var i ListPendingWorkspaceInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.InviterDisplayName,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceForCollaboration = `-- name: LockWorkspaceForCollaboration :one
SELECT id
FROM workspaces
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockWorkspaceForCollaboration(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockWorkspaceForCollaboration, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const removeWorkspaceMembership = `-- name: RemoveWorkspaceMembership :execrows
UPDATE workspace_members
SET removed_at = $3
WHERE workspace_id = $1
  AND user_id = $2
  AND removed_at IS NULL
`

type RemoveWorkspaceMembershipParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RemovedAt   pgtype.Timestamptz `json:"removed_at"`
}

func (q *Queries) RemoveWorkspaceMembership(ctx context.Context, arg RemoveWorkspaceMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeWorkspaceMembership, arg.WorkspaceID, arg.UserID, arg.RemovedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOpenWorkspaceInvitationsForEmail = `-- name: RevokeOpenWorkspaceInvitationsForEmail :exec
UPDATE workspace_invitations
SET revoked_at = $3
WHERE workspace_id = $1
  AND lower(email) = lower($2)
  AND accepted_at IS NULL
  AND revoked_at IS NULL
`

type RevokeOpenWorkspaceInvitationsForEmailParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Lower       string             `json:"lower"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeOpenWorkspaceInvitationsForEmail(ctx context.Context, arg RevokeOpenWorkspaceInvitationsForEmailParams) error {
	_, err := q.db.Exec(ctx, revokeOpenWorkspaceInvitationsForEmail, arg.WorkspaceID, arg.Lower, arg.RevokedAt)
	return err
}

const revokeWorkspaceInvitation = `-- name: RevokeWorkspaceInvitation :execrows
UPDATE workspace_invitations
SET revoked_at = $3
WHERE workspace_id = $1
  AND id = $2
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > $3
`

type RevokeWorkspaceInvitationParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeWorkspaceInvitation(ctx context.Context, arg RevokeWorkspaceInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeWorkspaceInvitation, arg.WorkspaceID, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWorkspaceMembershipRole = `-- name: UpdateWorkspaceMembershipRole :execrows
UPDATE workspace_members
SET role = $3
WHERE workspace_id = $1
  AND user_id = $2
  AND removed_at IS NULL
`

type UpdateWorkspaceMembershipRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) UpdateWorkspaceMembershipRole(ctx context.Context, arg UpdateWorkspaceMembershipRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWorkspaceMembershipRole, arg.WorkspaceID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
