// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_rates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestExchangeRates = `-- name: LatestExchangeRates :many
SELECT DISTINCT ON (quote_currency)
    rate_date,
    base_currency,
    quote_currency,
    rate,
    fetched_at
FROM exchange_rates
WHERE base_currency = $1
ORDER BY quote_currency, rate_date DESC
`

// One row per quote currency, each the most recently published rate for that pair.
func (q *Queries) LatestExchangeRates(ctx context.Context, baseCurrency string) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, latestExchangeRates, baseCurrency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.RateDate,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.Rate,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (
    rate_date, base_currency, quote_currency, rate
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (rate_date, base_currency, quote_currency)
DO UPDATE SET rate = EXCLUDED.rate, fetched_at = now()
`

type UpsertExchangeRateParams struct {
	RateDate      pgtype.Date    `json:"rate_date"`
	BaseCurrency  string         `json:"base_currency"`
	QuoteCurrency string         `json:"quote_currency"`
	Rate          pgtype.Numeric `json:"rate"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, upsertExchangeRate,
		arg.RateDate,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.Rate,
	)
	return err
}
