// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT COALESCE(SUM(entry.amount_minor), 0)::BIGINT AS balance_minor
FROM transaction_entries AS entry
JOIN transactions AS transaction ON transaction.id = entry.transaction_id
WHERE entry.workspace_id = $1
  AND entry.account_id = $2
  AND transaction.status = 'posted'
  AND transaction.deleted_at IS NULL
`

type GetAccountBalanceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AccountID   pgtype.UUID `json:"account_id"`
}

func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, arg.WorkspaceID, arg.AccountID)
	var balance_minor int64
	err := row.Scan(&balance_minor)
	return balance_minor, err
}

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now() AS database_time
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var database_time interface{}
	err := row.Scan(&database_time)
	return database_time, err
}
