// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Name            string             `json:"name"`
	Type            string             `json:"type"`
	Currency        string             `json:"currency"`
	InstitutionName pgtype.Text        `json:"institution_name"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Budget struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Period      string             `json:"period"`
	StartsOn    pgtype.Date        `json:"starts_on"`
	Rollover    bool               `json:"rollover"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BudgetItem struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	BudgetID        pgtype.UUID `json:"budget_id"`
	CategoryID      pgtype.UUID `json:"category_id"`
	AmountBaseMinor int64       `json:"amount_base_minor"`
}

type Category struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	Name          string             `json:"name"`
	Kind          string             `json:"kind"`
	SystemKey     pgtype.Text        `json:"system_key"`
	Icon          pgtype.Text        `json:"icon"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	PredefinedKey pgtype.Text        `json:"predefined_key"`
	IconType      string             `json:"icon_type"`
	IconValue     string             `json:"icon_value"`
	ColorKey      string             `json:"color_key"`
}

type ExchangeRate struct {
	RateDate      pgtype.Date        `json:"rate_date"`
	BaseCurrency  string             `json:"base_currency"`
	QuoteCurrency string             `json:"quote_currency"`
	Rate          pgtype.Numeric     `json:"rate"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	Transport  string             `json:"transport"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Kind            string             `json:"kind"`
	Status          string             `json:"status"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	Payee           pgtype.Text        `json:"payee"`
	Description     pgtype.Text        `json:"description"`
	Notes           pgtype.Text        `json:"notes"`
	Source          string             `json:"source"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type TransactionAllocation struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	AmountBaseMinor int64              `json:"amount_base_minor"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TransactionEntry struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	AmountMinor     int64              `json:"amount_minor"`
	BaseAmountMinor int64              `json:"base_amount_minor"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	BaseCurrency string             `json:"base_currency"`
	Timezone     string             `json:"timezone"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceInvitation struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	TokenHash   []byte             `json:"token_hash"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AcceptedBy  pgtype.UUID        `json:"accepted_by"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	RemovedAt   pgtype.Timestamptz `json:"removed_at"`
}
