// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReportingWorkspace = `-- name: GetReportingWorkspace :one
SELECT base_currency, timezone
FROM workspaces
WHERE id = $1
`

type GetReportingWorkspaceRow struct {
	BaseCurrency string `json:"base_currency"`
	Timezone     string `json:"timezone"`
}

func (q *Queries) GetReportingWorkspace(ctx context.Context, id pgtype.UUID) (GetReportingWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getReportingWorkspace, id)
	var i GetReportingWorkspaceRow
	err := row.Scan(&i.BaseCurrency, &i.Timezone)
	return i, err
}

const listReportingAccountBalances = `-- name: ListReportingAccountBalances :many
SELECT
    accounts.id,
    accounts.name,
    accounts.type,
    accounts.currency,
    accounts.archived_at,
    COALESCE(SUM(transaction_entries.amount_minor) FILTER (
        WHERE transactions.status = 'posted'
          AND transactions.deleted_at IS NULL
          AND transactions.transaction_date <= $1::DATE
    ), 0)::BIGINT AS posted_native_minor,
    COALESCE(SUM(transaction_entries.amount_minor) FILTER (
        WHERE transactions.status = 'pending'
          AND transactions.deleted_at IS NULL
          AND transactions.transaction_date <= $1::DATE
    ), 0)::BIGINT AS pending_native_minor,
    COALESCE(SUM(transaction_entries.base_amount_minor) FILTER (
        WHERE transactions.status = 'posted'
          AND transactions.deleted_at IS NULL
          AND transactions.transaction_date <= $1::DATE
    ), 0)::BIGINT AS posted_base_minor,
    COALESCE(SUM(transaction_entries.base_amount_minor) FILTER (
        WHERE transactions.status = 'pending'
          AND transactions.deleted_at IS NULL
          AND transactions.transaction_date <= $1::DATE
    ), 0)::BIGINT AS pending_base_minor
FROM accounts
LEFT JOIN transaction_entries
    ON transaction_entries.workspace_id = accounts.workspace_id
   AND transaction_entries.account_id = accounts.id
LEFT JOIN transactions
    ON transactions.workspace_id = transaction_entries.workspace_id
   AND transactions.id = transaction_entries.transaction_id
WHERE accounts.workspace_id = $2
GROUP BY accounts.id
ORDER BY accounts.archived_at NULLS FIRST, lower(accounts.name), accounts.id
`

type ListReportingAccountBalancesParams struct {
	ToDate      pgtype.Date `json:"to_date"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type ListReportingAccountBalancesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Type               string             `json:"type"`
	Currency           string             `json:"currency"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	PostedNativeMinor  int64              `json:"posted_native_minor"`
	PendingNativeMinor int64              `json:"pending_native_minor"`
	PostedBaseMinor    int64              `json:"posted_base_minor"`
	PendingBaseMinor   int64              `json:"pending_base_minor"`
}

func (q *Queries) ListReportingAccountBalances(ctx context.Context, arg ListReportingAccountBalancesParams) ([]ListReportingAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, listReportingAccountBalances, arg.ToDate, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportingAccountBalancesRow{}
	for rows.Next() {
		var i ListReportingAccountBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.ArchivedAt,
			&i.PostedNativeMinor,
			&i.PendingNativeMinor,
			&i.PostedBaseMinor,
			&i.PendingBaseMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportingCategoryActivity = `-- name: ListReportingCategoryActivity :many
WITH RECURSIVE category_ancestors AS (
    SELECT categories.id AS descendant_id, categories.id AS ancestor_id
    FROM categories
    WHERE categories.workspace_id = $1

    UNION ALL

    SELECT category_ancestors.descendant_id, parent.id AS ancestor_id
    FROM category_ancestors
    JOIN categories AS child
      ON child.workspace_id = $1
     AND child.id = category_ancestors.ancestor_id
    JOIN categories AS parent
      ON parent.workspace_id = child.workspace_id
     AND parent.id = child.parent_id
),
direct_activity AS (
    SELECT
        categories.id,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE transactions.status = 'posted'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $2::DATE
              AND transactions.transaction_date <= $3::DATE
        ), 0)::BIGINT AS direct_posted_signed_minor,
        COALESCE(SUM(transaction_allocations.amount_base_minor) FILTER (
            WHERE transactions.status = 'pending'
              AND transactions.deleted_at IS NULL
              AND transactions.transaction_date >= $2::DATE
              AND transactions.transaction_date <= $3::DATE
        ), 0)::BIGINT AS direct_pending_signed_minor
    FROM categories
    LEFT JOIN transaction_allocations
      ON transaction_allocations.workspace_id = categories.workspace_id
     AND transaction_allocations.category_id = categories.id
    LEFT JOIN transactions
      ON transactions.workspace_id = transaction_allocations.workspace_id
     AND transactions.id = transaction_allocations.transaction_id
    WHERE categories.workspace_id = $1
    GROUP BY categories.id
),
rolled_activity AS (
    SELECT
        category_ancestors.ancestor_id AS id,
        SUM(direct_activity.direct_posted_signed_minor)::BIGINT
            AS rolled_posted_signed_minor,
        SUM(direct_activity.direct_pending_signed_minor)::BIGINT
            AS rolled_pending_signed_minor
    FROM category_ancestors
    JOIN direct_activity
      ON direct_activity.id = category_ancestors.descendant_id
    GROUP BY category_ancestors.ancestor_id
)
SELECT
    categories.id,
    categories.parent_id,
    categories.name,
    categories.kind,
    categories.system_key,
    categories.icon,
    categories.archived_at,
    direct_activity.direct_posted_signed_minor,
    direct_activity.direct_pending_signed_minor,
    rolled_activity.rolled_posted_signed_minor,
    rolled_activity.rolled_pending_signed_minor
FROM categories
JOIN direct_activity ON direct_activity.id = categories.id
JOIN rolled_activity ON rolled_activity.id = categories.id
WHERE categories.workspace_id = $1
ORDER BY categories.kind, categories.parent_id NULLS FIRST, lower(categories.name), categories.id
`

type ListReportingCategoryActivityParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
}

type ListReportingCategoryActivityRow struct {
	ID                       pgtype.UUID        `json:"id"`
	ParentID                 pgtype.UUID        `json:"parent_id"`
	Name                     string             `json:"name"`
	Kind                     string             `json:"kind"`
	SystemKey                pgtype.Text        `json:"system_key"`
	Icon                     pgtype.Text        `json:"icon"`
	ArchivedAt               pgtype.Timestamptz `json:"archived_at"`
	DirectPostedSignedMinor  int64              `json:"direct_posted_signed_minor"`
	DirectPendingSignedMinor int64              `json:"direct_pending_signed_minor"`
	RolledPostedSignedMinor  int64              `json:"rolled_posted_signed_minor"`
	RolledPendingSignedMinor int64              `json:"rolled_pending_signed_minor"`
}

func (q *Queries) ListReportingCategoryActivity(ctx context.Context, arg ListReportingCategoryActivityParams) ([]ListReportingCategoryActivityRow, error) {
	rows, err := q.db.Query(ctx, listReportingCategoryActivity, arg.WorkspaceID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportingCategoryActivityRow{}
	for rows.Next() {
		var i ListReportingCategoryActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.SystemKey,
			&i.Icon,
			&i.ArchivedAt,
			&i.DirectPostedSignedMinor,
			&i.DirectPendingSignedMinor,
			&i.RolledPostedSignedMinor,
			&i.RolledPendingSignedMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
