// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (
    id, workspace_id, kind, status, transaction_date, payee, description, notes,
    source, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10
)
`

type CreateTransactionParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	Kind            string      `json:"kind"`
	Status          string      `json:"status"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Payee           pgtype.Text `json:"payee"`
	Description     pgtype.Text `json:"description"`
	Notes           pgtype.Text `json:"notes"`
	Source          string      `json:"source"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.Exec(ctx, createTransaction,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Status,
		arg.TransactionDate,
		arg.Payee,
		arg.Description,
		arg.Notes,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const createTransactionAllocation = `-- name: CreateTransactionAllocation :exec
INSERT INTO transaction_allocations (
    id, workspace_id, transaction_id, category_id, amount_base_minor
) VALUES ($1, $2, $3, $4, $5)
`

type CreateTransactionAllocationParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	TransactionID   pgtype.UUID `json:"transaction_id"`
	CategoryID      pgtype.UUID `json:"category_id"`
	AmountBaseMinor int64       `json:"amount_base_minor"`
}

func (q *Queries) CreateTransactionAllocation(ctx context.Context, arg CreateTransactionAllocationParams) error {
	_, err := q.db.Exec(ctx, createTransactionAllocation,
		arg.ID,
		arg.WorkspaceID,
		arg.TransactionID,
		arg.CategoryID,
		arg.AmountBaseMinor,
	)
	return err
}

const createTransactionEntry = `-- name: CreateTransactionEntry :exec
INSERT INTO transaction_entries (
    id, workspace_id, transaction_id, account_id, amount_minor, base_amount_minor
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTransactionEntryParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	TransactionID   pgtype.UUID `json:"transaction_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	AmountMinor     int64       `json:"amount_minor"`
	BaseAmountMinor int64       `json:"base_amount_minor"`
}

func (q *Queries) CreateTransactionEntry(ctx context.Context, arg CreateTransactionEntryParams) error {
	_, err := q.db.Exec(ctx, createTransactionEntry,
		arg.ID,
		arg.WorkspaceID,
		arg.TransactionID,
		arg.AccountID,
		arg.AmountMinor,
		arg.BaseAmountMinor,
	)
	return err
}

const deleteTransactionAllocations = `-- name: DeleteTransactionAllocations :exec
DELETE FROM transaction_allocations
WHERE workspace_id = $1 AND transaction_id = $2
`

type DeleteTransactionAllocationsParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
}

func (q *Queries) DeleteTransactionAllocations(ctx context.Context, arg DeleteTransactionAllocationsParams) error {
	_, err := q.db.Exec(ctx, deleteTransactionAllocations, arg.WorkspaceID, arg.TransactionID)
	return err
}

const deleteTransactionEntries = `-- name: DeleteTransactionEntries :exec
DELETE FROM transaction_entries
WHERE workspace_id = $1 AND transaction_id = $2
`

type DeleteTransactionEntriesParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
}

func (q *Queries) DeleteTransactionEntries(ctx context.Context, arg DeleteTransactionEntriesParams) error {
	_, err := q.db.Exec(ctx, deleteTransactionEntries, arg.WorkspaceID, arg.TransactionID)
	return err
}

const getSystemCategoryID = `-- name: GetSystemCategoryID :one
SELECT id
FROM categories
WHERE workspace_id = $1 AND system_key = $2
`

type GetSystemCategoryIDParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SystemKey   pgtype.Text `json:"system_key"`
}

func (q *Queries) GetSystemCategoryID(ctx context.Context, arg GetSystemCategoryIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSystemCategoryID, arg.WorkspaceID, arg.SystemKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT
    id, workspace_id, kind, status, transaction_date, payee, description, notes,
    source, created_by, updated_by, created_at, updated_at
FROM transactions
WHERE workspace_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetTransactionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetTransactionRow struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Kind            string             `json:"kind"`
	Status          string             `json:"status"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	Payee           pgtype.Text        `json:"payee"`
	Description     pgtype.Text        `json:"description"`
	Notes           pgtype.Text        `json:"notes"`
	Source          string             `json:"source"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.WorkspaceID, arg.ID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Status,
		&i.TransactionDate,
		&i.Payee,
		&i.Description,
		&i.Notes,
		&i.Source,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionAccountCurrency = `-- name: GetTransactionAccountCurrency :one
SELECT currency
FROM accounts
WHERE workspace_id = $1 AND id = $2
`

type GetTransactionAccountCurrencyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetTransactionAccountCurrency(ctx context.Context, arg GetTransactionAccountCurrencyParams) (string, error) {
	row := q.db.QueryRow(ctx, getTransactionAccountCurrency, arg.WorkspaceID, arg.ID)
	var currency string
	err := row.Scan(&currency)
	return currency, err
}

const listTransactionAllocations = `-- name: ListTransactionAllocations :many
SELECT transaction_id, id, category_id, amount_base_minor
FROM transaction_allocations
WHERE workspace_id = $1
  AND transaction_id = ANY($2::UUID[])
ORDER BY transaction_id, created_at, id
`

type ListTransactionAllocationsParams struct {
	WorkspaceID    pgtype.UUID   `json:"workspace_id"`
	TransactionIds []pgtype.UUID `json:"transaction_ids"`
}

type ListTransactionAllocationsRow struct {
	TransactionID   pgtype.UUID `json:"transaction_id"`
	ID              pgtype.UUID `json:"id"`
	CategoryID      pgtype.UUID `json:"category_id"`
	AmountBaseMinor int64       `json:"amount_base_minor"`
}

func (q *Queries) ListTransactionAllocations(ctx context.Context, arg ListTransactionAllocationsParams) ([]ListTransactionAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionAllocations, arg.WorkspaceID, arg.TransactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionAllocationsRow{}
	for rows.Next() {
		var i ListTransactionAllocationsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.ID,
			&i.CategoryID,
			&i.AmountBaseMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionEntries = `-- name: ListTransactionEntries :many
SELECT transaction_id, id, account_id, amount_minor, base_amount_minor
FROM transaction_entries
WHERE workspace_id = $1
  AND transaction_id = ANY($2::UUID[])
ORDER BY transaction_id, created_at, id
`

type ListTransactionEntriesParams struct {
	WorkspaceID    pgtype.UUID   `json:"workspace_id"`
	TransactionIds []pgtype.UUID `json:"transaction_ids"`
}

type ListTransactionEntriesRow struct {
	TransactionID   pgtype.UUID `json:"transaction_id"`
	ID              pgtype.UUID `json:"id"`
	AccountID       pgtype.UUID `json:"account_id"`
	AmountMinor     int64       `json:"amount_minor"`
	BaseAmountMinor int64       `json:"base_amount_minor"`
}

func (q *Queries) ListTransactionEntries(ctx context.Context, arg ListTransactionEntriesParams) ([]ListTransactionEntriesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionEntries, arg.WorkspaceID, arg.TransactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionEntriesRow{}
	for rows.Next() {
		var i ListTransactionEntriesRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.ID,
			&i.AccountID,
			&i.AmountMinor,
			&i.BaseAmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    id, workspace_id, kind, status, transaction_date, payee, description, notes,
    source, created_by, updated_by, created_at, updated_at
FROM transactions
WHERE workspace_id = $1
  AND deleted_at IS NULL
  AND ($2::DATE IS NULL OR transaction_date >= $2)
  AND ($3::DATE IS NULL OR transaction_date <= $3)
ORDER BY transaction_date DESC, created_at DESC, id DESC
LIMIT $4
`

type ListTransactionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
	ResultLimit int32       `json:"result_limit"`
}

type ListTransactionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Kind            string             `json:"kind"`
	Status          string             `json:"status"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	Payee           pgtype.Text        `json:"payee"`
	Description     pgtype.Text        `json:"description"`
	Notes           pgtype.Text        `json:"notes"`
	Source          string             `json:"source"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.WorkspaceID,
		arg.FromDate,
		arg.ToDate,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Status,
			&i.TransactionDate,
			&i.Payee,
			&i.Description,
			&i.Notes,
			&i.Source,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :execrows
UPDATE transactions
SET deleted_at = now(),
    updated_by = $1,
    updated_at = now()
WHERE workspace_id = $2
  AND id = $3
  AND deleted_at IS NULL
`

type SoftDeleteTransactionParams struct {
	UpdatedBy   pgtype.UUID `json:"updated_by"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransaction, arg.UpdatedBy, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transactionCategoryExists = `-- name: TransactionCategoryExists :one
SELECT EXISTS (
    SELECT 1 FROM categories WHERE workspace_id = $1 AND id = $2
)
`

type TransactionCategoryExistsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) TransactionCategoryExists(ctx context.Context, arg TransactionCategoryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, transactionCategoryExists, arg.WorkspaceID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTransaction = `-- name: UpdateTransaction :execrows
UPDATE transactions
SET kind = $1,
    status = $2,
    transaction_date = $3,
    payee = $4,
    description = $5,
    notes = $6,
    updated_by = $7,
    updated_at = now()
WHERE workspace_id = $8
  AND id = $9
  AND deleted_at IS NULL
`

type UpdateTransactionParams struct {
	Kind            string      `json:"kind"`
	Status          string      `json:"status"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Payee           pgtype.Text `json:"payee"`
	Description     pgtype.Text `json:"description"`
	Notes           pgtype.Text `json:"notes"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransaction,
		arg.Kind,
		arg.Status,
		arg.TransactionDate,
		arg.Payee,
		arg.Description,
		arg.Notes,
		arg.UpdatedBy,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
