// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspaceBaseCurrency = `-- name: GetWorkspaceBaseCurrency :one
SELECT base_currency
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceBaseCurrency(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBaseCurrency, id)
	var base_currency string
	err := row.Scan(&base_currency)
	return base_currency, err
}

const getWorkspaceMemberRole = `-- name: GetWorkspaceMemberRole :one
SELECT role
FROM workspace_members
WHERE workspace_id = $1
  AND user_id = $2
  AND removed_at IS NULL
`

type GetWorkspaceMemberRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceMemberRole(ctx context.Context, arg GetWorkspaceMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getWorkspaceName = `-- name: GetWorkspaceName :one
SELECT name
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceName(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
